#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

printf %s "
backend web-backend
        balance roundrobin
        option forwardfor
        server 252558-web-01 52.90.13.57:80 check
        server 252558-web-02 54.224.51.29:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
